
install_requirements:
	@pip install -r requirements.txt

start_streamlit:
	-@streamlit run app.py


install_on_dev:
	@pip install -e ../../    #install root package (detect AI content)
	@pip install -r requirements.txt
